apiVersion: apps/v1
kind: Deployment

metadata: 
  name: frontend-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: taha664/todo-app-frontend
          ports:
            - containerPort: 80