apiVersion: v1
kind: Pod

metadata:
  name: mongodb
  labels:
    name: mongodb

spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "taha"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "taha"