apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: monitoring-daemon

spec:
  selector:
    matchLabels:
      name: monitoring-agent
  template:
    metadata:
      labels:
        name: monitoring-agent
      spec:
        containers:
          - name: monitoring-agent
            image: nginx
            ports:
              - containerPort: 80